server:
  port: 9009
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test01?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
# JPA 配置内容，对应 JpaProperties 类
  jpa:
    show-sql: true
    # Hibernate 配置内容，对应 HibernateProperties 类
    hibernate:
      ddl-auto: none


