server:
  port: 9003

spring:
  application:
    name: admin-server



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/



